
language: python
python:
  - '3.5'

script:
    # API TESTS
    - behave tests/api/feature
    # DOMAIN TESTS
    - mamba tests/domain/
    - behave tests/domain/use_case/register


after_success:
    # Send coverage to Codecov
    - coverage run --source=domain -m behave tests/domain/use_case/register
    - bash <(curl -s https://codecov.io/bash) -t 209b6cec-bad0-4164-a594-0b08db97aca6
